const app = document.getElementById('app');
const search = document.getElementById('search');
const authModal = document.getElementById('auth');
const loginBtn = document.getElementById('loginBtn');
const logoutBtn = document.getElementById('logoutBtn');
const themeBtn = document.getElementById('themeBtn');
const tokenKey='zenithmax_token';
let token=localStorage.getItem(tokenKey)||'';
let me=null, view='home', videoCache=[], currentVideo=null, page=1, loading=false, hasMore=true, activeCategory='ALL';
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const fmt=n=>Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n||0);
const ago=s=>{const sec=Math.max(1,(Date.now()-new Date(s))/1000);if(sec<60)return Math.floor(sec)+'s ago';if(sec<3600)return Math.floor(sec/60)+'m ago';if(sec<86400)return Math.floor(sec/3600)+'h ago';return Math.floor(sec/86400)+'d ago'};
async function api(url,opt={}){opt.headers={...(opt.headers||{}),...(token?{Authorization:'Bearer '+token}:{})};const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Request failed');return d}
function needAuth(){if(!token){openAuth();return false}return true}
function setAuthUI(){loginBtn.classList.toggle('hidden',!!me);logoutBtn.classList.toggle('hidden',!me);loginBtn.textContent=me?me.name:'Sign in'}
async function boot(){if(token){try{me=(await api('/api/me')).user}catch{token='';localStorage.removeItem(tokenKey)}}setAuthUI();bind();render()}
function bind(){
  document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x===b));render()});
  search.addEventListener('keydown',e=>{if(e.key==='Enter'){view='search';render()}});
  let t;search.addEventListener('input',()=>{clearTimeout(t);t=setTimeout(showSuggestions,180)});
  loginBtn.onclick=()=>openAuth();logoutBtn.onclick=()=>{token='';me=null;localStorage.removeItem(tokenKey);setAuthUI();render()};
  themeBtn.onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem('zenith_theme',document.documentElement.classList.contains('light')?'light':'dark')};
  if(localStorage.getItem('zenith_theme')==='light')document.documentElement.classList.add('light');
  document.getElementById('closeAuth').onclick=()=>authModal.classList.add('hidden');
  let register=false;document.getElementById('switchAuth').onclick=()=>{register=!register;document.getElementById('name').classList.toggle('hidden',!register);document.getElementById('authTitle').textContent=register?'Join ZenithMax':'Welcome back';document.getElementById('authBtn').textContent=register?'Create Account':'Sign In';document.getElementById('switchAuth').textContent=register?'Already have an account? Sign in':'Create an account';document.getElementById('authBtn').dataset.register=register?'1':''};
  document.getElementById('authBtn').onclick=async()=>{const isReg=document.getElementById('authBtn').dataset.register==='1',body={email:document.getElementById('email').value,password:document.getElementById('password').value,name:document.getElementById('name').value};try{const d=await api('/api/auth/'+(isReg?'register':'login'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});token=d.token;me=d.user;localStorage.setItem(tokenKey,token);authModal.classList.add('hidden');setAuthUI();render()}catch(e){document.getElementById('authMsg').textContent=e.message}};
}
function openAuth(){authModal.classList.remove('hidden')}
async function showSuggestions(){let box=document.getElementById('suggestions');if(!box){box=document.createElement('div');box.id='suggestions';box.className='suggestions';search.parentElement?.appendChild(box);document.body.appendChild(box)}const q=search.value.trim();if(q.length<2){box.remove();return}const d=await api('/api/search/suggestions?q='+encodeURIComponent(q));const r=search.getBoundingClientRect();box.style.left=r.left+'px';box.style.top=(r.bottom+6)+'px';box.style.width=r.width+'px';box.innerHTML=d.suggestions.map(s=>`<button onclick="search.value='${esc(s).replace(/'/g,"\\'")}';view='search';document.getElementById('suggestions')?.remove();render()">${esc(s)}</button>`).join('');}
function hero(){return `<section class="hero"><div><span class="eyebrow">ZENITHMAX V16.1 · LAUNCH READY</span><h1>Watch. Create. Connect. Grow.</h1><p>Remote starter videos are ready from day one, with sound, Shorts, recommendations, creator channels, creator uploads for videos/music/games, media messaging, playlists and creator business tools.</p><div class="hero-actions"><button class="primary" onclick="view='shorts';render()">▶ Open Shorts</button><button class="ghost" onclick="view='discover';render()">Explore trending</button></div></div><div class="hero-orb"><span>V13</span><small>SMART FEED</small></div></section>`}
function card(v){return `<article class="video-card"><div class="thumb" onclick="watchVideo('${v.id}')"><video muted preload="metadata" src="${esc(v.url)}"></video><span class="duration">${v.duration?Math.max(1,Math.round(v.duration))+'s':'Video'}</span>${v.audio?'<span class="audio-badge">🔊 AUDIO</span>':''}${v.starter?'<span class="original">REMOTE DEMO</span>':''}</div><div class="card-body"><button class="avatar" onclick="openCreator('${v.creatorId}')">${esc((v.creator||'Z')[0])}</button><div class="meta"><h3 onclick="watchVideo('${v.id}')">${esc(v.title)}</h3><p onclick="openCreator('${v.creatorId}')">${esc(v.creator)} ${v.verified?'<span class="verified">✓</span>':''}</p><small>${esc(v.category||'GENERAL')} · ${fmt(v.views)} views · ${ago(v.createdAt)}</small>${v.license?`<small class="source-note">${esc(v.license)} · ${esc(v.sourceCreator||'Open media')}</small>`:''}${v.reason?`<small class="reason">✨ ${esc(v.reason)}</small>`:''}</div><button class="dots" onclick="videoMenu('${v.id}')">⋮</button></div></article>`}
function section(title,vs,sub=''){return `<section class="section"><div class="section-head"><div><h2>${esc(title)}</h2>${sub?`<p>${esc(sub)}</p>`:''}</div></div><div class="video-grid">${vs.map(card).join('')}</div></section>`}
async function render(){window.scrollTo({top:0,behavior:'instant'});app.innerHTML='<div class="loading">Loading ZenithMax…</div>';try{if(view==='home')return renderHome();if(view==='shorts')return renderShorts();if(view==='discover')return renderDiscover();if(view==='music')return renderMusic();if(view==='games')return renderGames();if(view==='following')return renderFollowing();if(view==='history')return renderHistory();if(view==='saved')return renderSaved();if(view==='playlists')return renderPlaylists();if(view==='studio')return renderStudio();if(view==='earn')return renderEarn();if(view==='messages')return renderMessages();if(view==='notifications')return renderNotifications();if(view==='profile')return renderProfile();if(view==='upload')return renderUpload();if(view==='about')return renderAbout();if(view==='search')return renderSearch()}catch(e){app.innerHTML=`<div class="panel"><h2>Something went wrong</h2><p>${esc(e.message)}</p></div>`}}
async function renderHome(){const [rec,tr,cre]=await Promise.all([api('/api/recommendations'),api('/api/trending'),api('/api/creators')]);videoCache=rec.videos;app.innerHTML=hero()+creatorRail(cre.creators.slice(0,10))+section('Recommended for you',rec.videos.slice(0,12),'Personalized by watch activity, follows and saves')+section('Trending now',tr.videos.slice(0,8),'Popular across ZenithMax');}
function creatorRail(cs){return `<section class="creator-rail"><div class="section-head"><h2>Creators to watch</h2></div><div class="creator-row">${cs.map(c=>`<button class="creator-chip" onclick="openCreator('${c.id}')"><span class="creator-avatar">${esc(c.name[0])}</span><b>${esc(c.name)} ${c.verified?'<span class="verified">✓</span>':''}</b><small>${fmt(c.followers)} followers</small></button>`).join('')}</div></section>`}
async function renderDiscover(){const d=await api('/api/discover');videoCache=d.videos;const cats=['ALL',...d.categories];app.innerHTML=`<div class="page-title"><span class="eyebrow">DISCOVER</span><h1>Find your next favorite video</h1></div><div class="category-row">${cats.map(c=>`<button class="category ${activeCategory===c?'active':''}" onclick="activeCategory='${esc(c)}';renderDiscover()">${esc(c)}</button>`).join('')}</div>`+section(activeCategory==='ALL'?'For you':activeCategory,d.videos.filter(v=>activeCategory==='ALL'||v.category===activeCategory).slice(0,60));}
async function renderSearch(){const q=search.value.trim();const d=await api('/api/videos?q='+encodeURIComponent(q)+'&sort=trending&limit=40');videoCache=d.videos;app.innerHTML=`<div class="page-title"><span class="eyebrow">SEARCH</span><h1>${d.total} results for “${esc(q)}”</h1></div>`+section('Videos',d.videos);}
async function renderFollowing(){if(!needAuth())return;const d=await api('/api/following');videoCache=d.videos;app.innerHTML=`<div class="page-title"><h1>Following</h1><p>Latest videos from creators you follow.</p></div>`+(d.videos.length?section('Your subscriptions',d.videos):'<div class="panel empty">Follow creators to build this feed.</div>')}
async function renderHistory(){if(!needAuth())return;const d=await api('/api/history');videoCache=d.videos;app.innerHTML=`<div class="page-title"><h1>Watch history</h1></div><div class="video-grid">${d.videos.map(v=>`<div>${card(v)}<div class="progress"><span style="width:${Math.round(v.progress||0)}%"></span></div></div>`).join('')}</div>`}
async function renderSaved(){if(!needAuth())return;const d=await api('/api/bookmarks');videoCache=d.videos;app.innerHTML=`<div class="page-title"><h1>Saved videos</h1></div>`+(d.videos.length?section('Watch later',d.videos):'<div class="panel empty">Save videos and they will appear here.</div>')}
async function renderPlaylists(){if(!needAuth())return;const d=await api('/api/playlists');app.innerHTML=`<div class="page-title row"><div><h1>Your playlists</h1><p>Build collections and play them anytime.</p></div><button class="primary" onclick="createPlaylist()">＋ New playlist</button></div><div class="playlist-grid">${d.playlists.map(p=>`<article class="playlist-card" onclick="openPlaylist('${p.id}')"><div class="playlist-cover">${p.cover?`<video muted src="${esc(p.cover)}"></video>`:'♫'}<span>${p.count} videos</span></div><h3>${esc(p.name)}</h3><p>${esc(p.description||'Private playlist')}</p></article>`).join('')||'<div class="panel empty">Create your first playlist.</div>'}</div>`}
async function createPlaylist(){const name=prompt('Playlist name');if(!name)return;const description=prompt('Description (optional)')||'';await api('/api/playlists',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,description})});renderPlaylists()}
async function openPlaylist(id){const d=await api('/api/playlists/'+id);videoCache=d.videos;app.innerHTML=`<div class="page-title row"><div><span class="eyebrow">PLAYLIST</span><h1>${esc(d.playlist.name)}</h1><p>${d.videos.length} videos · ${esc(d.playlist.description||'')}</p></div><button class="danger" onclick="deletePlaylist('${id}')">Delete</button></div>${d.videos.length?section('Videos',d.videos):'<div class="panel empty">No videos yet. Use the ⋮ menu on a video to add one.</div>'}`}
async function deletePlaylist(id){if(confirm('Delete this playlist?')){await api('/api/playlists/'+id,{method:'DELETE'});renderPlaylists()}}
async function renderNotifications(){if(!needAuth())return;const d=await api('/api/notifications');app.innerHTML=`<div class="page-title row"><div><h1>Notifications</h1><p>${d.notifications.filter(n=>!n.read).length} unread</p></div><button class="ghost" onclick="markNotificationsRead()">Mark all read</button></div><div class="notification-list">${d.notifications.map(n=>`<div class="notification ${n.read?'':'unread'}"><span>${n.type==='like'?'♥':n.type==='comment'?'💬':n.type==='follow'?'👤':n.type==='message'?'✉':'🔔'}</span><div><b>${esc(n.text)}</b><small>${ago(n.createdAt)}</small></div></div>`).join('')||'<div class="panel empty">No notifications yet.</div>'}</div>`}
async function markNotificationsRead(){await api('/api/notifications/read',{method:'POST'});renderNotifications()}
async function renderMessages(){if(!needAuth())return;const d=await api('/api/messages/conversations');app.innerHTML=`<div class="page-title"><h1>Messages</h1><p>Chat with creators and friends. You can send text, images, videos and audio.</p></div><div class="inbox">${d.conversations.map(c=>`<button class="conversation" onclick="openChat('${c.user.id}')"><span class="avatar">${esc(c.user.name[0])}</span><div><b>${esc(c.user.name)}</b><p>${esc(c.last.text||'Media message')}</p><small>${ago(c.last.createdAt)}</small></div></button>`).join('')||'<div class="panel empty">No conversations yet. Open a creator page and tap Message.</div>'}</div>`}
async function openChat(id){const d=await api('/api/messages/'+id);const bubbles=d.messages.map(m=>{let body=m.kind==='media'?(m.mediaType==='video'?`<video class="chat-media" controls playsinline src="${esc(m.url)}"></video>`:m.mediaType==='audio'?`<audio class="chat-audio" controls src="${esc(m.url)}"></audio>`:m.mediaType==='image'?`<img class="chat-image" src="${esc(m.url)}" alt="Shared image">`:`<a href="${esc(m.url)}" target="_blank">📎 ${esc(m.fileName||'Shared file')}</a>`) : `<p>${esc(m.text)}</p>`;return `<div class="bubble ${m.fromId===me.id?'mine':''}">${body}${m.text&&m.kind==='media'?`<p>${esc(m.text)}</p>`:''}<small>${ago(m.createdAt)}</small></div>`}).join('');app.innerHTML=`<div class="chat"><div class="chat-head"><button class="ghost" onclick="renderMessages()">←</button><span class="avatar">${esc(d.user?.name?.[0]||'U')}</span><div><b>${esc(d.user?.name||'User')}</b><small>Text, video, image & audio chat</small></div></div><div class="chat-body" id="chatBody">${bubbles||'<div class="panel empty">Start the conversation.</div>'}</div><form class="chat-compose" onsubmit="sendMessage(event,'${id}')"><input id="messageText" maxlength="1000" placeholder="Write a message…"><button class="primary">Send</button></form><form class="media-compose" onsubmit="sendMedia(event,'${id}')"><input id="mediaFile" type="file" accept="image/*,video/mp4,video/webm,video/quicktime,audio/mpeg,audio/mp4,audio/wav,audio/ogg,audio/webm" required><input id="mediaCaption" maxlength="300" placeholder="Caption (optional)"><button class="ghost">📎 Send media</button></form></div>`;setTimeout(()=>chatBody.scrollTop=chatBody.scrollHeight,30)}
async function sendMedia(e,id){e.preventDefault();if(!needAuth())return;const f=mediaFile.files[0];if(!f)return;const fd=new FormData();fd.append('media',f);fd.append('caption',mediaCaption.value.trim());try{await api('/api/messages/'+id+'/media',{method:'POST',body:fd});openChat(id)}catch(x){alert(x.message)}}
async function sendMessage(e,id){e.preventDefault();const text=messageText.value.trim();if(!text)return;await api('/api/messages/'+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});openChat(id)}
async function renderStudio(){if(!needAuth())return;const s=await api('/api/stats');app.innerHTML=`<div class="page-title"><span class="eyebrow">CREATOR STUDIO V13</span><h1>Channel analytics</h1><p>Track performance across your ZenithMax videos.</p></div><div class="statgrid"><div class="stat"><b>${fmt(s.videos)}</b><span>Videos</span></div><div class="stat"><b>${fmt(s.views)}</b><span>Views</span></div><div class="stat"><b>${fmt(s.likes)}</b><span>Likes</span></div><div class="stat"><b>${fmt(s.followers)}</b><span>Followers</span></div><div class="stat"><b>${fmt(s.comments)}</b><span>Comments</span></div></div><div class="dashboard-grid"><div class="panel"><h2>Top videos</h2>${s.topVideos.map((v,i)=>`<div class="rank"><b>#${i+1} ${esc(v.title)}</b><span>${fmt(v.views)} views · ${fmt(v.likes)} likes</span></div>`).join('')||'<p>No uploads yet.</p>'}</div><div class="panel"><h2>Category performance</h2>${Object.entries(s.categories).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="bar-row"><span>${esc(k)}</span><div><i style="width:${Math.min(100,v/Math.max(1,s.views)*100)}%"></i></div><b>${fmt(v)}</b></div>`).join('')||'<p>No data yet.</p>'}</div></div>${me?.role==='admin'?'<button class="ghost" onclick="renderAdmin()">Open moderation dashboard</button>':''}`}
async function renderEarn(){
  if(!needAuth())return;
  const d=await api('/api/monetization/dashboard');
  app.innerHTML=`<div class="page-title"><span class="eyebrow">ZENITHMAX V14</span><h1>Creator Earnings</h1><p>Build your audience and explore monetization tools. <b>Demo mode:</b> no real payments are processed.</p></div>
  <div class="statgrid"><div class="stat"><b>${fmt(d.summary.total)}</b><span>Total demo earnings</span></div><div class="stat"><b>${fmt(d.summary.tips)}</b><span>Tips</span></div><div class="stat"><b>${fmt(d.summary.subscriptions)}</b><span>Subscriptions</span></div><div class="stat"><b>${fmt(d.summary.ads)}</b><span>Ads</span></div><div class="stat"><b>${fmt(d.summary.sponsorships)}</b><span>Sponsorships</span></div><div class="stat"><b>${fmt(d.creatorSubscribers)}</b><span>Subscribers</span></div></div>
  <div class="dashboard-grid"><div class="panel"><h2>Creator support</h2><p class="muted">Fans can use demo credits to test tips and subscriptions. Real payment processing should be connected only after the business, age, tax, and payment requirements are handled appropriately.</p><div class="form-row"><button class="primary" onclick="demoTip()">💛 Test a tip</button><button class="ghost" onclick="createDemoCampaign()">📣 New ad campaign</button></div></div>
  <div class="panel"><h2>Monetization eligibility</h2><p>${d.eligible?'You currently meet the demo audience threshold.':'Keep building your audience before enabling creator monetization.'}</p><small class="muted">Demo threshold: 100 followers. Actual eligibility can vary by country, product, and payment provider.</small></div></div>
  <div class="panel" style="margin-top:18px"><div class="section-head"><div><h2>Ad campaigns</h2><p>Create promotional campaigns in demo mode.</p></div></div>${d.campaigns.map(c=>`<div class="report-row"><div><b>${esc(c.title)}</b><p>${fmt(c.budget)} demo credits · ${fmt(c.impressions)} impressions · ${fmt(c.clicks)} clicks</p></div><span class="status ${c.status==='active'?'open':''}">${esc(c.status)}</span><button class="ghost" onclick="toggleCampaign('${c.id}')">${c.status==='active'?'Pause':'Activate'}</button></div>`).join('')||'<p class="muted">No campaigns yet.</p>'}</div>
  <div class="panel" style="margin-top:18px"><h2>Recent earnings</h2>${d.history.map(e=>`<div class="rank"><b>${esc(e.type)}</b><span>+${fmt(e.amount)} credits · ${ago(e.createdAt)}</span></div>`).join('')||'<p class="muted">No earnings yet.</p>'}</div>`;
}
async function demoTip(){const creators=await api('/api/creators');const c=creators.creators.find(x=>x.id!==me.id);if(!c)return alert('No other creator available.');try{const r=await api('/api/monetization/tip',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({creatorId:c.id,amount:5})});alert(`Demo tip recorded: creator earned ${r.creatorEarned} credits.`);renderEarn()}catch(e){alert(e.message)}}
async function createDemoCampaign(){const title=prompt('Campaign name');if(!title)return;try{await api('/api/monetization/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,budget:100})});renderEarn()}catch(e){alert(e.message)}}
async function toggleCampaign(id){try{await api('/api/monetization/campaigns/'+id+'/activate',{method:'POST'});renderEarn()}catch(e){alert(e.message)}}
async function renderAdmin(){const d=await api('/api/admin/overview');app.innerHTML=`<div class="page-title"><span class="eyebrow">ADMIN</span><h1>Moderation dashboard</h1></div><div class="statgrid"><div class="stat"><b>${d.users}</b><span>Users</span></div><div class="stat"><b>${d.videos}</b><span>Videos</span></div><div class="stat"><b>${d.comments}</b><span>Comments</span></div><div class="stat"><b>${d.reports}</b><span>Open reports</span></div></div><div class="panel"><h2>Recent reports</h2>${d.recentReports.map(r=>`<div class="report-row"><div><b>${esc(r.title)}</b><p>${esc(r.reason)} · ${ago(r.createdAt)}</p></div><span class="status ${r.status}">${r.status}</span>${r.status==='open'?`<button class="ghost" onclick="resolveReport('${r.id}')">Resolve</button>`:''}</div>`).join('')||'<p>No reports.</p>'}</div>`}
async function resolveReport(id){await api('/api/admin/reports/'+id+'/resolve',{method:'POST'});renderAdmin()}
async function renderProfile(){if(!needAuth())return;app.innerHTML=`<div class="profile-hero"><div class="profile-banner"></div><div class="profile-main"><div class="avatar-xl">${esc(me.name[0])}</div><div><h1>${esc(me.name)} ${me.verified?'<span class="verified">✓</span>':''}</h1><p>${esc(me.bio||'')}</p><small>${fmt(me.followers)} followers · ${fmt(me.following)} following</small><p class="creator-status">${me.role==='creator'||me.role==='admin'?'🎬 Creator Mode is active':'👤 Viewer account'}</p></div><div class="creator-actions"><button class="ghost" onclick="editProfile()">Edit profile</button>${me.role==='creator'||me.role==='admin'?'':'<button class="primary" onclick="becomeCreator()">Become a Creator</button>'}</div></div></div>`}
async function becomeCreator(){if(!needAuth())return;try{const d=await api('/api/creator/apply',{method:'POST'});me=d.user;alert('Creator Mode is now active!');render()}catch(e){alert(e.message)}}
async function editProfile(){const name=prompt('Display name',me.name);if(!name)return;const bio=prompt('Bio',me.bio||'')??me.bio;const d=await api('/api/me',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,bio})});me=d.user;setAuthUI();renderProfile()}
async function renderAbout(){
  app.innerHTML=`<div class="page-title"><span class="eyebrow">ABOUT ZENITHMAX</span><h1>About the Developer</h1><p>Meet the person behind the ZenithMax platform and its continuing development.</p></div><div class="dashboard-grid"><section class="panel"><div class="avatar-xl" style="margin-bottom:16px">ZO</div><h2>Zenith Oluwambe</h2><p class="creator-status">Founder &amp; CEO · ZenithMax Technology Company</p><p>ZenithMax is an original platform project created and developed by Zenith Oluwambe. The project brings social media, video, music, games and creator tools together in one ecosystem.</p><p class="muted">Developer credit: Zenith Oluwambe · ZenithMax Technology Company</p></section><section class="panel"><h2>Project Credit</h2><p>Original design, product direction and development credit belong to the ZenithMax project and its developer. Third-party media, libraries and services remain subject to their own licenses and terms.</p><div class="tags"><span class="tag">ZenithMax</span><span class="tag">Original Project</span><span class="tag">Developer Credit</span></div></section></div>`;
}
function renderUpload(){
  if(!needAuth())return;
  app.innerHTML=`<div class="upload-shell"><div class="page-title"><span class="eyebrow">CREATE</span><h1>Upload to ZenithMax</h1><p>Publish videos, release music, or upload a browser-playable HTML5 game.</p></div>
  <div class="upload-tabs"><button class="primary" onclick="showUploadType('video')">🎬 Video</button><button class="ghost" onclick="showUploadType('music')">🎵 Music</button><button class="ghost" onclick="showUploadType('game')">🎮 Game</button></div><div id="uploadType"></div></div>`;
  showUploadType('video');
}
function showUploadType(type){
  const box=document.getElementById('uploadType');
  if(type==='video') box.innerHTML=`<form id="uploadForm" class="panel form"><h2>Upload a video</h2><label>Video title<input name="title" required maxlength="120" placeholder="Give your video a title"></label><label>Description<textarea name="description" rows="5" maxlength="2000" placeholder="Tell viewers about your video"></textarea></label><div class="form-row"><label>Category<input name="category" placeholder="SPORTS, TECH, COMEDY…"></label><label>Tags<input name="tags" placeholder="football, tutorial, short"></label></div><label class="file-drop">Choose video<input name="video" type="file" accept="video/mp4,video/webm,video/quicktime" required></label><button class="primary">Publish video</button><p id="uploadMsg"></p></form>`;
  if(type==='music') box.innerHTML=`<form id="musicForm" class="panel form"><h2>Upload music</h2><label>Track title<input name="title" required maxlength="120" placeholder="Song title"></label><div class="form-row"><label>Artist<input name="artist" maxlength="80" placeholder="Artist name"></label><label>Album<input name="album" maxlength="120" placeholder="Album or single"></label></div><label>Genre<input name="genre" maxlength="60" placeholder="Afrobeats, Pop, Hip-hop…"></label><label>Description<textarea name="description" rows="4" maxlength="1000" placeholder="Tell listeners about the track"></textarea></label><label class="file-drop">Choose audio<input name="audio" type="file" accept="audio/*" required></label><button class="primary">Publish music</button><p id="musicMsg"></p></form>`;
  if(type==='game') box.innerHTML=`<form id="gameForm" class="panel form"><h2>Upload a playable game</h2><p class="muted">Games must be browser-based HTML5 projects packed as a ZIP with an <b>index.html</b> entry point. Executable PC/APK files are not accepted.</p><label>Game title<input name="title" required maxlength="120" placeholder="Game title"></label><div class="form-row"><label>Genre<input name="genre" maxlength="60" placeholder="Racing, Football, Puzzle…"></label><label>Version<input name="version" maxlength="30" value="1.0.0"></label></div><label>Description<textarea name="description" rows="4" maxlength="1200" placeholder="Tell players about the game"></textarea></label><label class="file-drop">Choose HTML5 game ZIP<input name="game" type="file" accept=".zip,application/zip" required></label><button class="primary">Publish game</button><p id="gameMsg"></p></form>`;
  const form=box.querySelector('form');
  if(!form)return;
  form.onsubmit=async e=>{e.preventDefault();const msg=box.querySelector('p:last-child');msg.textContent='Uploading…';try{const endpoint=type==='video'?'/api/videos':type==='music'?'/api/music':'/api/games';await api(endpoint,{method:'POST',body:new FormData(e.target)});msg.textContent=type==='video'?'Video published!':type==='music'?'Music published!':'Game published!';setTimeout(()=>render(),700)}catch(x){msg.textContent=x.message}};
}
async function renderMusic(){const d=await api('/api/music');app.innerHTML=`<div class="page-title"><span class="eyebrow">MUSIC</span><h1>ZenithMax Music</h1><p>Listen to music uploaded by ZenithMax creators.</p></div><div class="music-list">${d.music.map(m=>`<article class="panel music-row"><div class="music-art">🎵</div><div class="music-meta"><h2>${esc(m.title)}</h2><p>${esc(m.artist||'Creator')} · ${esc(m.genre||'GENERAL')} ${m.album?`· ${esc(m.album)}`:''}</p><audio controls preload="metadata" src="${esc(m.url)}" onplay="fetch('/api/music/${m.id}/play',{method:'POST'})"></audio></div><small>${fmt(m.plays||0)} plays</small></article>`).join('')||'<div class="panel"><h2>No music yet</h2><p>Upload the first track from Creator Uploads.</p></div>'}</div>`}
async function renderGames(){const d=await api('/api/games');app.innerHTML=`<div class="page-title"><span class="eyebrow">GAMES</span><h1>ZenithMax Games</h1><p>Play browser games uploaded by creators.</p></div><div class="video-grid">${d.games.map(g=>`<article class="video-card"><div class="thumb game-thumb"><div class="game-icon">🎮</div><span class="duration">${esc(g.genre||'GAME')}</span></div><div class="card-body"><div class="meta"><h3>${esc(g.title)}</h3><p>${esc(g.creator||'Creator')}</p><small>${fmt(g.plays||0)} plays · v${esc(g.version||'1.0.0')}</small></div><button class="primary" onclick="playGame('${g.id}')">▶ Play</button></div></article>`).join('')||'<div class="panel"><h2>No games yet</h2><p>Upload an HTML5 game from Creator Uploads.</p></div>'}</div>`}
function playGame(id){app.innerHTML=`<div class="game-player"><div class="page-title"><button class="ghost" onclick="view='games';render()">← Games</button><h1>Loading game…</h1></div><iframe title="ZenithMax game" class="game-frame" src="/api/games/${id}/play" sandbox="allow-scripts allow-pointer-lock allow-forms allow-popups" allow="autoplay; fullscreen" loading="eager"></iframe></div>`}
async function renderShorts(){const d=await api('/api/recommendations');videoCache=d.videos;app.innerHTML=`<div class="shorts-toolbar"><button class="ghost" onclick="view='home';render()">← Home</button><b>ZenithMax Shorts</b><button class="ghost" id="globalMute" onclick="toggleShortsMute()">🔇 Sound off</button></div><div class="shorts-shell" id="shortsShell">${d.videos.slice(0,80).map((v,i)=>shortItem(v,i)).join('')}</div>`;setTimeout(initShorts,30)}
function shortItem(v,i){return `<section class="short-slide" data-id="${v.id}"><div class="short-stage"><video class="short-video" loop muted playsinline preload="${i<3?'auto':'metadata'}" src="${esc(v.url)}"></video><button class="sound-btn" onclick="toggleSound(this)">🔇</button><div class="short-gradient"></div><div class="short-copy"><button class="short-creator" onclick="openCreator('${v.creatorId}')"><span class="avatar-lg">${esc((v.creator||'Z')[0])}</span><span><b>@${esc((v.creator||'creator').replace(/\s+/g,'').toLowerCase())} ${v.verified?'✓':''}</b><small>${esc(v.category||'SHORTS')} · ${fmt(v.views)} views</small></span></button><h2>${esc(v.title)}</h2><p>${esc(v.description||'')}</p><small class="reason">✨ ${esc(v.reasons?.[0]||v.reason||'Recommended for you')}</small></div><div class="short-actions"><button onclick="likeVideo('${v.id}',this)"><span>${v.liked?'♥':'♡'}</span><small>${fmt(v.likes)}</small></button><button onclick="openComments('${v.id}')"><span>💬</span><small>${v.commentCount||'Comment'}</small></button><button onclick="saveVideo('${v.id}',this)"><span>${v.saved?'★':'☆'}</span><small>Save</small></button><button onclick="shareVideo('${v.id}')"><span>↗</span><small>Share</small></button><button onclick="videoMenu('${v.id}')"><span>⋯</span><small>More</small></button></div></div></section>`}
let shortsIO;function initShorts(){const slides=[...document.querySelectorAll('.short-slide')],vids=slides.map(s=>s.querySelector('video'));slides.forEach((s,i)=>{s.addEventListener('click',e=>{if(e.target.closest('button'))return;const v=s.querySelector('video');v.paused?v.play().catch(()=>{}):v.pause()});s.addEventListener('wheel',e=>{if(Math.abs(e.deltaY)<25)return;e.preventDefault();slides[Math.max(0,Math.min(slides.length-1,i+(e.deltaY>0?1:-1)))].scrollIntoView({behavior:'smooth'})},{passive:false})});shortsIO=new IntersectionObserver(es=>es.forEach(e=>{const v=e.target.querySelector('video');if(e.isIntersecting&&e.intersectionRatio>.72){vids.forEach(x=>x!==v&&x.pause());v.play().catch(()=>{});viewVideo(e.target.dataset.id)}else v.pause()}),{threshold:[.72]});slides.forEach(s=>shortsIO.observe(s));let y=0;shortsShell.addEventListener('touchstart',e=>y=e.touches[0].clientY,{passive:true});shortsShell.addEventListener('touchend',e=>{const dy=y-e.changedTouches[0].clientY;if(Math.abs(dy)>50){const cur=slides.findIndex(s=>s.getBoundingClientRect().top>-40&&s.getBoundingClientRect().top<innerHeight/2),next=Math.max(0,Math.min(slides.length-1,cur+(dy>0?1:-1)));slides[next].scrollIntoView({behavior:'smooth'})}},{passive:true})}
function toggleSound(btn){const v=btn.parentElement.querySelector('video');v.muted=!v.muted;btn.textContent=v.muted?'🔇':'🔊'}function toggleShortsMute(){const vs=document.querySelectorAll('.short-video'),muted=[...vs].some(v=>v.muted);vs.forEach(v=>v.muted=!muted);globalMute.textContent=muted?'🔊 Sound on':'🔇 Sound off'}
async function watchVideo(id){let v=videoCache.find(x=>x.id===id);if(!v){const d=await api('/api/videos?limit=40');v=d.videos.find(x=>x.id===id)}if(!v)return;currentVideo=v;const rec=(await api('/api/recommendations?videoId='+encodeURIComponent(id))).videos;app.innerHTML=`<div class="watch-layout"><div class="watch-main"><div class="player-frame"><video id="mainPlayer" controls autoplay playsinline preload="auto" src="${esc(v.url)}"></video></div><div class="watch-head"><div><h1>${esc(v.title)}</h1><div class="watch-byline"><button class="creator-link" onclick="openCreator('${v.creatorId}')"><span class="mini-avatar">${esc((v.creator||'Z')[0])}</span><b>${esc(v.creator)} ${v.verified?'<span class="verified">✓</span>':''}</b></button> · ${fmt(v.views)} views</div></div><div class="watch-buttons"><button onclick="likeVideo('${v.id}',this)">${v.liked?'♥':'♡'} ${fmt(v.likes)}</button><button onclick="saveVideo('${v.id}',this)">${v.saved?'★ Saved':'☆ Save'}</button><button onclick="shareVideo('${v.id}')">↗ Share</button><button onclick="videoMenu('${v.id}')">⋯</button></div></div><div class="description-box"><b>${esc(v.category||'Video')} · ${fmt(v.views)} views</b><p>${esc(v.description||'')}</p><div class="tags">${(v.tags||[]).map(t=>`#${esc(t)}`).join(' ')}</div></div><div class="comments-box"><div class="comments-head"><h2>Comments</h2><span id="commentCount">Loading…</span></div><div id="commentsList"></div><div class="comment-compose"><input id="commentInput" maxlength="500" placeholder="Add a comment…"><button class="primary" onclick="postComment('${v.id}')">Post</button></div></div></div><aside class="up-next"><h3>Up next</h3>${rec.slice(0,18).map(r=>`<div class="next-card" onclick="watchVideo('${r.id}')"><video muted preload="metadata" src="${esc(r.url)}"></video><div><b>${esc(r.title)}</b><small>${esc(r.creator)} ${r.verified?'✓':''}</small><small>${fmt(r.views)} views</small><small class="reason">${esc(r.reasons?.[0]||'Recommended')}</small></div></div>`).join('')}</aside></div>`;mainPlayer.addEventListener('play',()=>viewVideo(id),{once:true});let last=0;mainPlayer.addEventListener('timeupdate',()=>{if(token&&mainPlayer.duration&&mainPlayer.currentTime-last>5){last=mainPlayer.currentTime;fetch('/api/videos/'+id+'/progress',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({progress:mainPlayer.currentTime/mainPlayer.duration*100})}).catch(()=>{})}});loadComments(id)}
async function loadComments(id){const d=await api('/api/videos/'+id+'/comments');commentCount.textContent=d.comments.length+' comments';commentsList.innerHTML=d.comments.map(c=>`<div class="comment"><div class="mini-avatar">${esc((c.user||'U')[0])}</div><div><b>${esc(c.user)} ${c.verified?'✓':''}</b><p>${esc(c.text)}</p><small>${ago(c.createdAt)}</small></div>${me&&c.userId===me.id?`<button class="dots" onclick="deleteComment('${c.id}','${id}')">×</button>`:''}</div>`).join('')||'<p class="muted">Be the first to comment.</p>'}
async function postComment(id){if(!needAuth())return;const text=commentInput.value.trim();if(!text)return;await api('/api/videos/'+id+'/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});commentInput.value='';loadComments(id)}
async function deleteComment(cid,vid){await api('/api/comments/'+cid,{method:'DELETE'});loadComments(vid)}
async function openComments(id){watchVideo(id);setTimeout(()=>document.querySelector('.comments-box')?.scrollIntoView({behavior:'smooth'}),80)}
async function openCreator(id){const d=await api('/api/users/'+id);videoCache=d.videos;app.innerHTML=`<div class="channel-hero"><div class="channel-banner"></div><div class="channel-main"><div class="avatar-xl">${esc(d.user.name[0])}</div><div class="channel-copy"><h1>${esc(d.user.name)} ${d.user.verified?'<span class="verified">✓</span>':''}</h1><p>${fmt(d.user.followers)} followers · ${d.videos.length} videos</p><p>${esc(d.user.bio||'')}</p></div>${me?.id!==id?`<div class="creator-actions"><button class="primary" onclick="followCreator('${id}',this)">${d.following?'Following':'Follow'}</button>${token?`<button class="ghost" onclick="openChat('${id}')">Message</button>`:''}</div>`:''}</div></div><div class="channel-tabs"><b>VIDEOS</b><span>SHORTS</span><span>ABOUT</span></div><div class="video-grid">${d.videos.map(card).join('')}</div>`}
async function followCreator(id,btn){if(!needAuth())return;const d=await api('/api/users/'+id+'/follow',{method:'POST'});btn.textContent=d.following?'Following':'Follow'}
async function likeVideo(id,btn){if(!needAuth())return;const d=await api('/api/videos/'+id+'/like',{method:'POST'});if(btn)btn.innerHTML=`${d.liked?'♥':'♡'} ${fmt(d.likes)}`}
async function saveVideo(id,btn){if(!needAuth())return;const d=await api('/api/videos/'+id+'/bookmark',{method:'POST'});if(btn)btn.innerHTML=d.saved?'★ Saved':'☆ Save'}
async function viewVideo(id){fetch('/api/videos/'+id+'/view',{method:'POST',headers:token?{Authorization:'Bearer '+token}:{}}).catch(()=>{})}
async function shareVideo(id){const u=location.origin+'/#video-'+id;try{await navigator.clipboard.writeText(u);alert('Video link copied')}catch{prompt('Copy this link:',u)}}
async function videoMenu(id){const choice=prompt('Video options:\n1 = Save / unsave\n2 = Add to playlist\n3 = Report\n4 = Copy link');if(choice==='1')return saveVideo(id);if(choice==='2')return addToPlaylist(id);if(choice==='3')return reportVideo(id);if(choice==='4')return shareVideo(id)}
async function addToPlaylist(id){if(!needAuth())return;const d=await api('/api/playlists');if(!d.playlists.length){alert('Create a playlist first.');view='playlists';return render()}const names=d.playlists.map((p,i)=>`${i+1}. ${p.name}`).join('\n');const n=Number(prompt('Choose playlist:\n'+names));const p=d.playlists[n-1];if(!p)return;const r=await api(`/api/playlists/${p.id}/videos/${id}`,{method:'POST'});alert(r.added?'Added to playlist':'Removed from playlist')}
async function reportVideo(id){if(!needAuth())return;const reason=prompt('Why are you reporting this video?');if(!reason)return;try{await api('/api/videos/'+id+'/report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});alert('Report submitted for review.')}catch(e){alert(e.message)}}
boot();
